name: Testing PR
on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  run-check:
    uses: ./.github/workflows/testing.yml
 