name: Test PR
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm test
      
