name: Test PR
on: [push, pull_request]
jobs:
  unint-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start unit-tests
        run: npm test
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      #- name: Start app
      #  run: npm start & npx wait-on http://localhost:3000
      - name: Download playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Start e2e tests
        run: npm run e2e
