name: Test PR
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start app
        run: npm start & npx wait-on http://localhost:3000
      - name: Download playwright browsers
        run: npx playwright install
      - name: Start e2e tests
        run: npm run e2e
      - name: Start unit-tests
        run: npm test
      
